local http = require("http")
local json = require("json")
local client = http.client()
local request = http.request("GET", "https://ipapi.co/120.229.14.207/json/")
local result, err = client:do_request(request)
if err then error(err) end
-- print(result.body)
local ip = json.decode(result.body)
print(ip.ip)
print(ip.org)
print(ip.country_name)
print(ip.region)
print(ip.city)

-- local tb = json.decode('{"a":1,"b":"ss","c":{"c1":1,"c2":2},"d":[10,11],"1":100}')
-- print(tb.c.c2)
